// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: miniJavaScanner.flex


@SuppressWarnings("fallthrough")
public class MiniJavaLexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int COMMENT = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\4\22\0\1\5\1\6"+
    "\1\7\2\0\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\12\23\1\24\1\25"+
    "\1\26\1\27\1\26\2\0\24\30\1\31\5\30\1\32"+
    "\1\0\1\33\1\0\1\34\1\0\1\35\1\36\1\37"+
    "\1\40\1\41\1\42\1\43\1\44\1\45\1\30\1\46"+
    "\1\47\1\50\1\51\1\52\1\53\1\30\1\54\1\55"+
    "\1\56\1\57\1\60\1\61\1\62\2\30\1\63\1\64"+
    "\1\65\1\66\6\0\1\3\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\3\1\4\1\5\1\1\1\6"+
    "\1\7\1\1\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\16\25\1\30\1\31\1\32\1\33\1\34"+
    "\1\2\2\34\1\35\1\34\1\23\1\0\1\36\1\37"+
    "\1\0\1\40\1\41\1\42\1\43\1\0\1\20\1\44"+
    "\1\0\13\25\1\45\13\25\1\46\2\35\1\47\1\43"+
    "\1\50\1\51\1\20\1\0\7\25\1\50\3\25\1\52"+
    "\1\53\13\25\1\20\1\54\4\25\1\55\2\25\1\56"+
    "\2\25\1\57\3\25\1\60\1\25\1\61\1\25\1\20"+
    "\1\62\1\63\1\64\2\25\1\65\1\66\5\25\1\67"+
    "\1\0\2\25\1\70\1\71\1\25\1\72\1\73\1\25";

  private static int [] zzUnpackAction() {
    int [] result = new int[163];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\67\0\156\0\245\0\156\0\156\0\334\0\u0113"+
    "\0\156\0\u014a\0\u0181\0\156\0\156\0\156\0\u01b8\0\156"+
    "\0\u01ef\0\156\0\u0226\0\u025d\0\156\0\156\0\334\0\334"+
    "\0\u0294\0\156\0\156\0\u02cb\0\u0302\0\u0339\0\u0370\0\u03a7"+
    "\0\u03de\0\u0415\0\u044c\0\u0483\0\u04ba\0\u04f1\0\u0528\0\u055f"+
    "\0\u0596\0\156\0\u05cd\0\156\0\156\0\u0604\0\u063b\0\u0672"+
    "\0\u06a9\0\u06e0\0\u0717\0\156\0\u0113\0\156\0\156\0\u074e"+
    "\0\156\0\156\0\156\0\u0785\0\u07bc\0\u07f3\0\156\0\u082a"+
    "\0\u0861\0\u0898\0\u08cf\0\u0906\0\u093d\0\u0974\0\u09ab\0\u09e2"+
    "\0\u0a19\0\u0a50\0\u0a87\0\u0294\0\u0abe\0\u0af5\0\u0b2c\0\u0b63"+
    "\0\u0b9a\0\u0bd1\0\u0c08\0\u0c3f\0\u0c76\0\u0cad\0\u0ce4\0\156"+
    "\0\u0d1b\0\u0d52\0\156\0\u0d89\0\156\0\u07bc\0\u0dc0\0\u0df7"+
    "\0\u0e2e\0\u0e65\0\u0e9c\0\u0ed3\0\u0f0a\0\u0f41\0\u0f78\0\u0294"+
    "\0\u0faf\0\u0fe6\0\u101d\0\u0294\0\u0294\0\u1054\0\u108b\0\u10c2"+
    "\0\u10f9\0\u1130\0\u1167\0\u119e\0\u11d5\0\u120c\0\u1243\0\u127a"+
    "\0\u12b1\0\156\0\u12e8\0\u131f\0\u1356\0\u138d\0\u0294\0\u13c4"+
    "\0\u13fb\0\u0294\0\u1432\0\u1469\0\u0294\0\u14a0\0\u14d7\0\u150e"+
    "\0\u0294\0\u1545\0\u0294\0\u157c\0\u15b3\0\u0294\0\u0294\0\u0294"+
    "\0\u15ea\0\u1621\0\u0294\0\u0294\0\u1658\0\u168f\0\u16c6\0\u16fd"+
    "\0\u1734\0\u0294\0\u176b\0\u17a2\0\u17d9\0\u0294\0\u0294\0\u1810"+
    "\0\u0294\0\u0294\0\u1847";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[163];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\2\4\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\2\31"+
    "\1\32\1\33\1\3\1\31\1\34\1\35\1\36\1\37"+
    "\1\40\2\31\1\41\3\31\1\42\1\31\1\43\1\44"+
    "\1\45\1\46\1\47\1\50\1\51\1\31\1\52\1\53"+
    "\1\54\1\55\1\56\1\57\1\5\1\56\2\57\1\56"+
    "\1\60\2\56\1\61\2\56\1\62\4\56\1\63\44\56"+
    "\70\0\1\4\2\0\2\4\110\0\1\64\37\0\7\65"+
    "\1\66\57\65\11\0\1\67\55\0\2\70\3\0\62\70"+
    "\16\0\1\71\70\0\1\72\63\0\1\73\4\0\1\74"+
    "\65\0\1\75\1\0\1\76\5\0\1\77\25\0\1\77"+
    "\14\0\1\100\15\0\1\31\4\0\2\31\2\0\27\31"+
    "\11\0\1\100\15\0\1\31\4\0\2\31\2\0\16\31"+
    "\1\101\1\31\1\102\6\31\11\0\1\100\15\0\1\31"+
    "\4\0\2\31\2\0\10\31\1\103\2\31\1\104\2\31"+
    "\1\105\10\31\11\0\1\100\15\0\1\31\4\0\2\31"+
    "\2\0\16\31\1\106\10\31\11\0\1\100\15\0\1\31"+
    "\4\0\2\31\2\0\13\31\1\107\2\31\1\110\7\31"+
    "\1\111\11\0\1\100\15\0\1\31\4\0\2\31\2\0"+
    "\1\31\1\112\11\31\1\113\13\31\11\0\1\100\15\0"+
    "\1\31\4\0\2\31\2\0\6\31\1\114\6\31\1\115"+
    "\11\31\11\0\1\100\15\0\1\31\4\0\2\31\2\0"+
    "\5\31\1\116\15\31\1\117\3\31\11\0\1\100\15\0"+
    "\1\31\4\0\2\31\2\0\20\31\1\120\6\31\11\0"+
    "\1\100\15\0\1\31\4\0\2\31\2\0\5\31\1\121"+
    "\21\31\11\0\1\100\15\0\1\31\4\0\2\31\2\0"+
    "\22\31\1\122\2\31\1\123\1\31\11\0\1\100\15\0"+
    "\1\31\4\0\2\31\2\0\20\31\1\124\6\31\11\0"+
    "\1\100\15\0\1\31\4\0\2\31\2\0\15\31\1\125"+
    "\11\31\11\0\1\100\15\0\1\31\4\0\2\31\2\0"+
    "\16\31\1\126\10\31\11\0\1\100\15\0\1\31\4\0"+
    "\2\31\2\0\10\31\1\127\16\31\70\0\1\130\2\0"+
    "\2\56\1\0\12\56\1\0\52\56\1\57\1\0\1\56"+
    "\2\57\7\56\1\0\51\56\2\60\1\65\4\60\1\56"+
    "\5\60\1\65\51\60\2\56\1\0\12\56\1\70\51\56"+
    "\2\131\1\0\12\131\1\132\4\131\1\133\44\131\2\56"+
    "\1\0\12\56\1\73\4\56\1\134\44\56\12\0\1\135"+
    "\54\0\2\74\3\0\62\74\23\0\1\136\64\0\1\75"+
    "\1\0\1\137\5\0\1\77\25\0\1\77\14\0\1\100"+
    "\22\0\2\140\3\0\26\140\11\0\1\100\15\0\1\31"+
    "\4\0\2\31\2\0\16\31\1\141\10\31\11\0\1\100"+
    "\15\0\1\31\4\0\2\31\2\0\5\31\1\142\21\31"+
    "\11\0\1\100\15\0\1\31\4\0\2\31\2\0\1\31"+
    "\1\143\25\31\11\0\1\100\15\0\1\31\4\0\2\31"+
    "\2\0\1\31\1\144\25\31\11\0\1\100\15\0\1\31"+
    "\4\0\2\31\2\0\15\31\1\145\11\31\11\0\1\100"+
    "\15\0\1\31\4\0\2\31\2\0\23\31\1\146\3\31"+
    "\11\0\1\100\15\0\1\31\4\0\2\31\2\0\21\31"+
    "\1\147\5\31\11\0\1\100\15\0\1\31\4\0\2\31"+
    "\2\0\13\31\1\150\13\31\11\0\1\100\15\0\1\31"+
    "\4\0\2\31\2\0\22\31\1\151\4\31\11\0\1\100"+
    "\15\0\1\31\4\0\2\31\2\0\13\31\1\152\13\31"+
    "\11\0\1\100\15\0\1\31\4\0\2\31\2\0\16\31"+
    "\1\153\10\31\11\0\1\100\15\0\1\31\4\0\2\31"+
    "\2\0\22\31\1\154\4\31\11\0\1\100\15\0\1\31"+
    "\4\0\2\31\2\0\25\31\1\155\1\31\11\0\1\100"+
    "\15\0\1\31\4\0\2\31\2\0\13\31\1\156\13\31"+
    "\11\0\1\100\15\0\1\31\4\0\2\31\2\0\11\31"+
    "\1\157\4\31\1\160\10\31\11\0\1\100\15\0\1\31"+
    "\4\0\2\31\2\0\1\31\1\161\20\31\1\162\4\31"+
    "\11\0\1\100\15\0\1\31\4\0\2\31\2\0\20\31"+
    "\1\163\6\31\11\0\1\100\15\0\1\31\4\0\2\31"+
    "\2\0\11\31\1\164\15\31\11\0\1\100\15\0\1\31"+
    "\4\0\2\31\2\0\23\31\1\165\3\31\11\0\1\100"+
    "\15\0\1\31\4\0\2\31\2\0\21\31\1\166\5\31"+
    "\11\0\1\100\15\0\1\31\4\0\2\31\2\0\11\31"+
    "\1\167\15\31\11\0\1\100\15\0\1\31\4\0\2\31"+
    "\2\0\11\31\1\170\15\31\4\0\2\131\1\0\12\131"+
    "\1\0\4\131\1\0\46\131\1\0\12\131\1\132\4\131"+
    "\1\0\44\131\2\134\1\0\2\56\10\134\1\74\51\134"+
    "\21\0\1\75\1\0\1\171\5\0\1\77\25\0\1\77"+
    "\22\0\1\172\7\0\1\140\4\0\2\140\2\0\27\140"+
    "\11\0\1\100\15\0\1\31\4\0\2\31\2\0\13\31"+
    "\1\154\13\31\11\0\1\100\15\0\1\31\4\0\2\31"+
    "\2\0\1\31\1\173\25\31\11\0\1\100\15\0\1\31"+
    "\4\0\2\31\2\0\20\31\1\154\6\31\11\0\1\100"+
    "\15\0\1\31\4\0\2\31\2\0\21\31\1\174\5\31"+
    "\11\0\1\100\15\0\1\31\4\0\2\31\2\0\21\31"+
    "\1\175\5\31\11\0\1\100\15\0\1\31\4\0\2\31"+
    "\2\0\2\31\1\176\24\31\11\0\1\100\15\0\1\31"+
    "\4\0\2\31\2\0\5\31\1\177\21\31\11\0\1\100"+
    "\15\0\1\31\4\0\2\31\2\0\5\31\1\200\21\31"+
    "\11\0\1\100\15\0\1\31\4\0\2\31\2\0\21\31"+
    "\1\201\5\31\11\0\1\100\15\0\1\31\4\0\2\31"+
    "\2\0\1\31\1\115\25\31\11\0\1\100\15\0\1\31"+
    "\4\0\2\31\2\0\13\31\1\202\13\31\11\0\1\100"+
    "\15\0\1\31\4\0\2\31\2\0\15\31\1\203\11\31"+
    "\11\0\1\100\15\0\1\31\4\0\2\31\2\0\7\31"+
    "\1\204\17\31\11\0\1\100\15\0\1\31\4\0\2\31"+
    "\2\0\4\31\1\205\22\31\11\0\1\100\15\0\1\31"+
    "\4\0\2\31\2\0\23\31\1\206\3\31\11\0\1\100"+
    "\15\0\1\31\4\0\2\31\2\0\11\31\1\207\15\31"+
    "\11\0\1\100\15\0\1\31\4\0\2\31\2\0\22\31"+
    "\1\210\4\31\11\0\1\100\15\0\1\31\4\0\2\31"+
    "\2\0\5\31\1\211\21\31\11\0\1\100\15\0\1\31"+
    "\4\0\2\31\2\0\11\31\1\212\15\31\11\0\1\100"+
    "\15\0\1\31\4\0\2\31\2\0\4\31\1\213\22\31"+
    "\11\0\1\100\15\0\1\31\4\0\2\31\2\0\13\31"+
    "\1\214\13\31\25\0\1\75\1\0\1\215\5\0\1\77"+
    "\25\0\1\77\14\0\1\100\15\0\1\31\4\0\2\31"+
    "\2\0\12\31\1\216\14\31\11\0\1\100\15\0\1\31"+
    "\4\0\2\31\2\0\21\31\1\217\5\31\11\0\1\100"+
    "\15\0\1\31\4\0\2\31\2\0\22\31\1\220\4\31"+
    "\11\0\1\100\15\0\1\31\4\0\2\31\2\0\13\31"+
    "\1\221\13\31\11\0\1\100\15\0\1\31\4\0\2\31"+
    "\2\0\15\31\1\222\11\31\11\0\1\100\15\0\1\31"+
    "\4\0\2\31\2\0\5\31\1\223\21\31\11\0\1\100"+
    "\15\0\1\31\4\0\2\31\2\0\22\31\1\224\4\31"+
    "\11\0\1\100\15\0\1\31\4\0\2\31\2\0\20\31"+
    "\1\225\6\31\11\0\1\100\15\0\1\31\4\0\2\31"+
    "\2\0\20\31\1\226\6\31\11\0\1\100\15\0\1\31"+
    "\4\0\2\31\2\0\15\31\1\227\11\31\11\0\1\100"+
    "\15\0\1\31\4\0\2\31\2\0\3\31\1\230\23\31"+
    "\11\0\1\100\15\0\1\31\4\0\2\31\2\0\7\31"+
    "\1\231\17\31\11\0\1\100\15\0\1\31\4\0\2\31"+
    "\2\0\5\31\1\232\21\31\25\0\1\75\1\0\1\233"+
    "\5\0\1\77\25\0\1\77\14\0\1\100\15\0\1\31"+
    "\4\0\2\31\2\0\5\31\1\154\21\31\11\0\1\100"+
    "\15\0\1\31\4\0\2\31\2\0\4\31\1\234\22\31"+
    "\11\0\1\100\15\0\1\31\4\0\2\31\2\0\1\31"+
    "\1\235\25\31\11\0\1\100\15\0\1\31\4\0\2\31"+
    "\2\0\15\31\1\236\11\31\11\0\1\100\15\0\1\31"+
    "\4\0\2\31\2\0\7\31\1\154\17\31\11\0\1\100"+
    "\15\0\1\31\4\0\2\31\2\0\10\31\1\237\16\31"+
    "\11\0\1\100\15\0\1\31\4\0\2\31\2\0\15\31"+
    "\1\240\11\31\25\0\1\75\1\0\1\233\50\0\1\100"+
    "\15\0\1\31\4\0\2\31\2\0\21\31\1\241\5\31"+
    "\11\0\1\100\15\0\1\31\4\0\2\31\2\0\14\31"+
    "\1\242\12\31\11\0\1\100\15\0\1\31\4\0\2\31"+
    "\2\0\5\31\1\243\21\31\11\0\1\100\15\0\1\31"+
    "\4\0\2\31\2\0\4\31\1\154\22\31\4\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[6270];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\1\1\2\11\2\1\1\11\2\1\3\11"+
    "\1\1\1\11\1\1\1\11\2\1\2\11\3\1\2\11"+
    "\16\1\1\11\1\1\2\11\6\1\1\11\1\0\2\11"+
    "\1\0\3\11\1\1\1\0\1\1\1\11\1\0\27\1"+
    "\1\11\2\1\1\11\1\1\1\11\2\1\1\0\31\1"+
    "\1\11\40\1\1\0\10\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[163];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    private java.io.BufferedWriter writer = null;

    private void initWriterIfNeeded() {
        if (writer == null) {
            try {
                writer = new java.io.BufferedWriter(new java.io.FileWriter("saIDa.txt"));
            } catch (java.io.IOException e) {
                System.err.println("Erro ao abrir o arquivo de saída: " + e.getMessage());
                System.exit(1);
            }
        }
    }

    public void closeWriter() {
        if (writer != null) {
            try {
                writer.close();
            } catch (java.io.IOException e) {
                System.err.println("Erro ao fechar o arquivo de saída: " + e.getMessage());
            }
        }
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public MiniJavaLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public int yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return YYEOF;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { throw new Error("Erro léxico: símbolo inválIDo '" + yytext() + "' na linha " + (yyline + 1) + ", coluna " + (yycolumn + 1));
            }
          // fall through
          case 60: break;
          case 2:
            { /* ignora espaços */
            }
          // fall through
          case 61: break;
          case 3:
            { /* ignora nova linha */
            }
          // fall through
          case 62: break;
          case 4:
            { System.out.print(yytext());
            }
          // fall through
          case 63: break;
          case 5:
            { initWriterIfNeeded(); writer.write("<" + yytext() + ", NOT>\n");
            }
          // fall through
          case 64: break;
          case 6:
            { initWriterIfNeeded(); writer.write("<" + yytext() + ", MOD>\n");
            }
          // fall through
          case 65: break;
          case 7:
            { initWriterIfNeeded(); writer.write("<" + yytext() + ", APERSAND>\n");
            }
          // fall through
          case 66: break;
          case 8:
            { initWriterIfNeeded(); writer.write("<" + yytext() + ", I_PAREN>\n");
            }
          // fall through
          case 67: break;
          case 9:
            { initWriterIfNeeded(); writer.write("<" + yytext() + ", F_PAREN>\n");
            }
          // fall through
          case 68: break;
          case 10:
            { initWriterIfNeeded(); writer.write("<" + yytext() + ", TIMES>\n");
            }
          // fall through
          case 69: break;
          case 11:
            { initWriterIfNeeded(); writer.write("<" + yytext() + ", PLUS>\n");
            }
          // fall through
          case 70: break;
          case 12:
            { initWriterIfNeeded(); writer.write("<" + yytext() + ", COMMA>\n");
            }
          // fall through
          case 71: break;
          case 13:
            { initWriterIfNeeded(); writer.write("<" + yytext() + ", MINUS>\n");
            }
          // fall through
          case 72: break;
          case 14:
            { initWriterIfNeeded(); writer.write("<" + yytext() + ", DOT>\n");
            }
          // fall through
          case 73: break;
          case 15:
            { initWriterIfNeeded(); writer.write("<" + yytext() + ", DIV>\n");
            }
          // fall through
          case 74: break;
          case 16:
            { initWriterIfNeeded(); writer.write("<" + yytext() + ", NUM_INT>\n");
            }
          // fall through
          case 75: break;
          case 17:
            { initWriterIfNeeded(); writer.write("<" + yytext() + ", COLON>\n");
            }
          // fall through
          case 76: break;
          case 18:
            { initWriterIfNeeded(); writer.write("<" + yytext() + ", SEMICOLON>\n");
            }
          // fall through
          case 77: break;
          case 19:
            { initWriterIfNeeded(); writer.write("<" + yytext() + ", RELOP>\n");
            }
          // fall through
          case 78: break;
          case 20:
            { initWriterIfNeeded(); writer.write("<" + yytext() + ", ASSIGN>\n");
            }
          // fall through
          case 79: break;
          case 21:
            { initWriterIfNeeded(); writer.write("<" + yytext() + ", ID>\n");
            }
          // fall through
          case 80: break;
          case 22:
            { initWriterIfNeeded(); writer.write("<" + yytext() + ", LSQUARE_BRACKET>\n");
            }
          // fall through
          case 81: break;
          case 23:
            { initWriterIfNeeded(); writer.write("<" + yytext() + ", RSQUARE_BRACKET>\n");
            }
          // fall through
          case 82: break;
          case 24:
            { initWriterIfNeeded(); writer.write("<" + yytext() + ", LBRACKET>\n");
            }
          // fall through
          case 83: break;
          case 25:
            { initWriterIfNeeded(); writer.write("<" + yytext() + ", ORB>\n");
            }
          // fall through
          case 84: break;
          case 26:
            { initWriterIfNeeded(); writer.write("<" + yytext() + ", RBRACKET>\n");
            }
          // fall through
          case 85: break;
          case 27:
            { initWriterIfNeeded(); writer.write("<" + yytext() + ", NOTB>\n");
            }
          // fall through
          case 86: break;
          case 28:
            { /* ignora conteúdo do comentário */
            }
          // fall through
          case 87: break;
          case 29:
            { /* ignora asteriscos */
            }
          // fall through
          case 88: break;
          case 30:
            { initWriterIfNeeded(); writer.write("<" + yytext() + ", STRING>\n");
            }
          // fall through
          case 89: break;
          case 31:
            { initWriterIfNeeded(); writer.write("<" + yytext() + ", AND>\n");
            }
          // fall through
          case 90: break;
          case 32:
            { initWriterIfNeeded(); writer.write("<" + yytext() + ", PLUS_PLUS>\n");
            }
          // fall through
          case 91: break;
          case 33:
            { initWriterIfNeeded(); writer.write("<" + yytext() + ", MINUS_MINUS>\n");
            }
          // fall through
          case 92: break;
          case 34:
            { yybegin(COMMENT);
            }
          // fall through
          case 93: break;
          case 35:
            { /* ignora comentários de linha */
            }
          // fall through
          case 94: break;
          case 36:
            { initWriterIfNeeded(); writer.write("<" + yytext() + ", UNSIGNED_NUMBER>\n");
            }
          // fall through
          case 95: break;
          case 37:
            { initWriterIfNeeded(); writer.write("<" + yytext() + ", IF>\n");
            }
          // fall through
          case 96: break;
          case 38:
            { initWriterIfNeeded(); writer.write("<" + yytext() + ", OR>\n");
            }
          // fall through
          case 97: break;
          case 39:
            { yybegin(YYINITIAL);
            }
          // fall through
          case 98: break;
          case 40:
            { initWriterIfNeeded(); writer.write("<" + yytext() + ", CHAR>\n");
            }
          // fall through
          case 99: break;
          case 41:
            { initWriterIfNeeded(); writer.write("<" + yytext() + ", REAL>\n");
            }
          // fall through
          case 100: break;
          case 42:
            { initWriterIfNeeded(); writer.write("<" + yytext() + ", TYPE>\n");
            }
          // fall through
          case 101: break;
          case 43:
            { initWriterIfNeeded(); writer.write("<" + yytext() + ", NEW>\n");
            }
          // fall through
          case 102: break;
          case 44:
            { initWriterIfNeeded(); writer.write("<" + yytext() + ", _START_METHOD_DECL>\n");
            }
          // fall through
          case 103: break;
          case 45:
            { initWriterIfNeeded(); writer.write("<" + yytext() + ", ELSE>\n");
            }
          // fall through
          case 104: break;
          case 46:
            { initWriterIfNeeded(); writer.write("<" + yytext() + ", NULL>\n");
            }
          // fall through
          case 105: break;
          case 47:
            { initWriterIfNeeded(); writer.write("<" + yytext() + ", READ>\n");
            }
          // fall through
          case 106: break;
          case 48:
            { initWriterIfNeeded(); writer.write("<" + yytext() + ", TRUE>\n");
            }
          // fall through
          case 107: break;
          case 49:
            { initWriterIfNeeded(); writer.write("<" + yytext() + ", VOID>\n");
            }
          // fall through
          case 108: break;
          case 50:
            { initWriterIfNeeded(); writer.write("<" + yytext() + ", BREAK>\n");
            }
          // fall through
          case 109: break;
          case 51:
            { initWriterIfNeeded(); writer.write("<" + yytext() + ", CLASS>\n");
            }
          // fall through
          case 110: break;
          case 52:
            { initWriterIfNeeded(); writer.write("<" + yytext() + ", CONST>\n");
            }
          // fall through
          case 111: break;
          case 53:
            { initWriterIfNeeded(); writer.write("<" + yytext() + ", FALSE>\n");
            }
          // fall through
          case 112: break;
          case 54:
            { initWriterIfNeeded(); writer.write("<" + yytext() + ", PRINTF>\n");
            }
          // fall through
          case 113: break;
          case 55:
            { initWriterIfNeeded(); writer.write("<" + yytext() + ", WHILE>\n");
            }
          // fall through
          case 114: break;
          case 56:
            { initWriterIfNeeded(); writer.write("<" + yytext() + ", RETURN>\n");
            }
          // fall through
          case 115: break;
          case 57:
            { initWriterIfNeeded(); writer.write("<" + yytext() + ", SWITCH>\n");
            }
          // fall through
          case 116: break;
          case 58:
            { initWriterIfNeeded(); writer.write("<" + yytext() + ", EXTENDS>\n");
            }
          // fall through
          case 117: break;
          case 59:
            { initWriterIfNeeded(); writer.write("<" + yytext() + ", PROGRAM>\n");
            }
          // fall through
          case 118: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String[] argv) {
    if (argv.length == 0) {
      System.out.println("Usage : java MiniJavaLexer [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          // Side-effect: is encodingName valid?
          java.nio.charset.Charset.forName(encodingName);
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        MiniJavaLexer scanner = null;
        java.io.FileInputStream stream = null;
        java.io.Reader reader = null;
        try {
          stream = new java.io.FileInputStream(argv[i]);
          reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new MiniJavaLexer(reader);
          while ( !scanner.zzAtEOF ) scanner.yylex();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
        finally {
          if (reader != null) {
            try {
              reader.close();
            }
            catch (java.io.IOException e) {
              System.out.println("IO error closing file \""+argv[i]+"\"");
              System.out.println(e);
            }
          }
          if (stream != null) {
            try {
              stream.close();
            }
            catch (java.io.IOException e) {
              System.out.println("IO error closing file \""+argv[i]+"\"");
              System.out.println(e);
            }
          }
        }
      }
    }
  }


}
